import * as d from "./datatypes.ts";
import * as m from "./mappers.ts";
import type { Datatype, PropertiesMap } from "./types.ts";

export const PROPERTIES_CONFIG: PropertiesMap = {
  accentColor: { toCss: "accent-color", datatype: d.color },
  alignContent: { toCss: "align-content", datatype: d.alignContent },
  alignItems: { toCss: "align-items", datatype: d.alignItems },
  alignSelf: { toCss: "align-self", datatype: d.alignSelf },
  appearance: { toCss: "appearance", datatype: d.appearance },
  aspectRatio: { toCss: "aspect-ratio", datatype: d.aspectRatio },
  backdropFilter: { toCss: "backdrop-filter", datatype: d.effects },
  background: { toCss: "background", datatype: d.color },
  backgroundColor: { toCss: "background-color", datatype: d.color },
  backgroundPosition: { toCss: "background-position", datatype: d.backgroundPosition },
  backgroundSize: { toCss: "background-size", datatype: d.backgroundSize },
  border: { toCss: "border", datatype: d.border },
  borderBottomWidth: { toCss: "border-bottom-width", datatype: d.borderWidth },
  borderCollapse: { toCss: "border-collapse", datatype: d.borderCollapse },
  borderColor: { toCss: "border-color", datatype: d.color },
  borderLeftWidth: { toCss: "border-left-width", datatype: d.borderWidth },
  borderRadius: { toCss: "border-radius", datatype: d.borderRadius },
  borderRadiusBottom: { toCss: ["border-bottom-left-radius", "border-bottom-right-radius"], datatype: d.borderRadius },
  borderRadiusEnd: { toCss: ["border-start-end-radius", "border-end-end-radius"], datatype: d.borderRadius },
  borderRadiusLeft: { toCss: ["border-top-left-radius", "border-bottom-left-radius"], datatype: d.borderRadius },
  borderRadiusRight: { toCss: ["border-top-right-radius", "border-bottom-right-radius"], datatype: d.borderRadius },
  borderRadiusStart: { toCss: ["border-start-start-radius", "border-end-start-radius"], datatype: d.borderRadius },
  borderRadiusTop: { toCss: ["border-top-left-radius", "border-top-right-radius"], datatype: d.borderRadius },
  borderRightWidth: { toCss: "border-right-width", datatype: d.borderWidth },
  borderStyle: { toCss: "border-style", datatype: d.borderStyle },
  borderTopWidth: { toCss: "border-top-width", datatype: d.borderWidth },
  borderWidth: { toCss: "border-width", datatype: d.borderWidth },
  bottom: { toCss: "bottom", datatype: d.distance },
  boxShadow: { toCss: "box-shadow", datatype: d.boxShadow },
  boxSizing: { toCss: "box-sizing", datatype: d.boxSizing },
  caretColor: { toCss: "caret-color", datatype: d.color },
  clip: { toCss: "clip", datatype: d.clip },
  color: { toCss: "color", datatype: d.color },
  colorScheme: { toCss: "color-scheme", datatype: d.colorScheme },
  columnGap: { toCss: "column-gap", datatype: d.spacing },
  content: { toCss: "content", datatype: d.content },
  cornerShape: { toCss: "corner-shape", datatype: d.cornerShape },
  cursor: { toCss: "cursor", datatype: d.cursor },
  display: { toCss: "display", datatype: d.display },
  filter: { toCss: "filter", datatype: d.effects },
  flex: { toCss: "flex", datatype: d.flex },
  flexBasis: { toCss: "flex-basis", datatype: d.size },
  flexDirection: { toCss: "flex-direction", datatype: d.flexDirection },
  flexGrow: { toCss: "flex-grow", datatype: d.flexSize },
  flexShrink: { toCss: "flex-shrink", datatype: d.flexSize },
  flexWrap: { toCss: "flex-wrap", datatype: d.flexWrap },
  font: { toCss: "font", datatype: d.font },
  fontFamily: { toCss: "font-family", datatype: d.fontFamily },
  fontFeatureSettings: { toCss: "font-feature-settings" },
  fontSize: { toCss: "font-size", datatype: d.fontSize },
  fontStyle: { toCss: "font-style", datatype: d.fontStyle },
  fontVariationSettings: { toCss: "font-variation-settings" },
  fontWeight: { toCss: "font-weight", datatype: d.fontWeight },
  gap: { toCss: "gap", datatype: d.spacing },
  gridAutoColumns: { toCss: "grid-auto-columns", datatype: d.gridTemplate },
  gridAutoFlow: { toCss: "grid-auto-flow", datatype: d.gridAutoFlow },
  gridAutoRows: { toCss: "grid-auto-rows", datatype: d.gridTemplate },
  gridColumn: { toCss: "grid-column", datatype: d.gridPosition },
  gridRow: { toCss: "grid-row", datatype: d.gridPosition },
  gridTemplateAreas: { toCss: "grid-template-areas", datatype: d.gridTemplateAreas },
  gridTemplateColumns: { toCss: "grid-template-columns", datatype: d.gridTemplate },
  gridTemplateRows: { toCss: "grid-template-rows", datatype: d.gridTemplate },
  height: { toCss: "height", datatype: d.size },
  inset: { toCss: "inset", datatype: d.distance },
  insetBlock: { toCss: "inset-block", datatype: d.distance },
  insetBlockEnd: { toCss: "inset-block-end", datatype: d.distance },
  insetBlockStart: { toCss: "inset-block-start", datatype: d.distance },
  insetInline: { toCss: "inset-inline", datatype: d.distance },
  insetInlineEnd: { toCss: "inset-inline-end", datatype: d.distance },
  insetInlineStart: { toCss: "inset-inline-start", datatype: d.distance },
  isolation: { toCss: "isolation", datatype: d.isolation },
  justifyContent: { toCss: "justify-content", datatype: d.justifyContent },
  justifyItems: { toCss: "justify-items", datatype: d.justifyItems },
  justifySelf: { toCss: "justify-self", datatype: d.justifySelf },
  left: { toCss: "left", datatype: d.distance },
  letterSpacing: { toCss: "letter-spacing", datatype: d.letterSpacing },
  lineHeight: { toCss: "line-height", datatype: d.lineHeight },
  listStyle: { toCss: "list-style", datatype: d.listStyle },
  margin: { toCss: "margin", datatype: d.spacing },
  marginBottom: { toCss: "margin-bottom", datatype: d.spacing },
  marginInlineEnd: { toCss: "margin-inline-end", datatype: d.spacing },
  marginInlineStart: { toCss: "margin-inline-start", datatype: d.spacing },
  marginLeft: { toCss: "margin-left", datatype: d.spacing },
  marginRight: { toCss: "margin-right", datatype: d.spacing },
  marginTop: { toCss: "margin-top", datatype: d.spacing },
  marginX: { toCss: ["margin-left", "margin-right"], datatype: d.spacing },
  marginY: { toCss: ["margin-top", "margin-bottom"], datatype: d.spacing },
  maxHeight: { toCss: "max-height", datatype: d.size },
  maxWidth: { toCss: "max-width", datatype: d.size },
  minHeight: { toCss: "min-height", datatype: d.size },
  minWidth: { toCss: "min-width", datatype: d.size },
  mixBlendMode: { toCss: "mix-blend-mode", datatype: d.mixBlendMode },
  objectFit: { toCss: "object-fit", datatype: d.objectFit },
  objectPosition: { toCss: "object-position", datatype: d.objectPosition },
  opacity: { toCss: "opacity", datatype: d.opacity },
  order: { toCss: "order", datatype: d.order },
  outline: { toCss: "outline", datatype: d.outline },
  outlineColor: { toCss: "outline-color", datatype: d.color },
  outlineOffset: { toCss: "outline-offset", datatype: d.borderWidth },
  outlineStyle: { toCss: "outline-style", datatype: d.borderStyle },
  outlineWidth: { toCss: "outline-width", datatype: d.borderWidth },
  overflow: { toCss: "overflow", datatype: d.overflow },
  overflowWrap: { toCss: "overflow-wrap", datatype: d.overflowWrap },
  overflowX: { toCss: "overflow-x", datatype: d.overflow },
  overflowY: { toCss: "overflow-y", datatype: d.overflow },
  overscrollBehavior: { toCss: "overscroll-behavior", datatype: d.overscrollBehavior },
  overscrollBehaviorX: { toCss: "overscroll-behavior-x", datatype: d.overscrollBehavior },
  overscrollBehaviorY: { toCss: "overscroll-behavior-y", datatype: d.overscrollBehavior },
  padding: { toCss: "padding", datatype: d.spacing },
  paddingBlock: { toCss: "padding-block", datatype: d.spacing },
  paddingBottom: { toCss: "padding-bottom", datatype: d.spacing },
  paddingInline: { toCss: "padding-inline", datatype: d.spacing },
  paddingInlineEnd: { toCss: "padding-inline-end", datatype: d.spacing },
  paddingInlineStart: { toCss: "padding-inline-start", datatype: d.spacing },
  paddingLeft: { toCss: "padding-left", datatype: d.spacing },
  paddingRight: { toCss: "padding-right", datatype: d.spacing },
  paddingTop: { toCss: "padding-top", datatype: d.spacing },
  paddingX: { toCss: ["padding-left", "padding-right"], datatype: d.spacing },
  paddingY: { toCss: ["padding-top", "padding-bottom"], datatype: d.spacing },
  placeContent: { toCss: "place-content", datatype: d.placeContent },
  placeItems: { toCss: "place-items", datatype: d.placeItems },
  placeSelf: { toCss: "place-self", datatype: d.placeSelf },
  pointerEvents: { toCss: "pointer-events", datatype: d.pointerEvents },
  position: { toCss: "position", datatype: d.position },
  positionArea: { toCss: "position-area", datatype: d.positionArea },
  resize: { toCss: "resize", datatype: d.resize },
  right: { toCss: "right", datatype: d.distance },
  rowGap: { toCss: "row-gap", datatype: d.spacing },
  scrollbarWidth: { toCss: "scrollbar-width", datatype: d.scrollbarWidth },
  scrollBehavior: { toCss: "scroll-behavior", datatype: d.scrollBehavior },
  scrollSnapAlign: { toCss: "scroll-snap-align", datatype: d.scrollSnapAlign },
  scrollSnapStop: { toCss: "scroll-snap-stop", datatype: d.scrollSnapStop },
  scrollSnapType: { toCss: "scroll-snap-type", datatype: d.scrollSnapType },
  tableLayout: { toCss: "table-layout", datatype: d.tableLayout },
  tabSize: { toCss: "tab-size" },
  textAlign: { toCss: "text-align", datatype: d.textAlign },
  textDecoration: { toCss: "text-decoration", datatype: d.textDecoration },
  textIndent: { toCss: "text-indent", datatype: d.distance },
  textOverflow: { toCss: "text-overflow", datatype: d.textOverflow },
  textTransform: { toCss: "text-transform", datatype: d.textTransform },
  top: { toCss: "top", datatype: d.distance },
  transform: { toCss: "transform", datatype: d.transform },
  transition: { toCss: "transition", datatype: d.transition },
  translate: { toCss: "translate", datatype: d.translate },
  userSelect: { toCss: "user-select", datatype: d.userSelect },
  verticalAlign: { toCss: "vertical-align", datatype: d.verticalAlign },
  visibility: { toCss: "visibility", datatype: d.visibility },
  WebkitAppearance: { toCss: "-webkit-appearance", datatype: d.appearance },
  WebkitOverflowScrolling: { toCss: "-webkit-overflow-scrolling", datatype: d.webkitOverflowScrolling },
  WebkitTapHighlightColor: { toCss: "-webkit-tap-highlight-color" },
  WebkitTextDecoration: { toCss: "-webkit-text-decoration", datatype: d.textDecoration },
  WebkitTextSizeAdjust: { toCss: "-webkit-text-size-adjust" },
  whiteSpace: { toCss: "white-space", datatype: d.whiteSpace },
  width: { toCss: "width", datatype: d.size },
  willChange: { toCss: "will-change", datatype: d.willChange },
  wordBreak: { toCss: "word-break", datatype: d.wordBreak },
  zIndex: { toCss: "z-index", datatype: d.zIndex },
};

export const VARIABLE_TYPE: Datatype = {
  mappers: [m.cssVarStr, m.cssVar, m.cssExpr, m.anyString],
};
