// This file is auto-generated by scripts/cssProperties.ts. Do not edit manually.
import type { tokens } from "@dldc/hono-ui";
import type { AnyStringValue, ColorOpacityValue, CssExprValue, CssVarStrValue, CssVarValue, PxValue, RawValue } from "./mappers.ts";

export interface CssObjProperties {
  padding?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingX?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingY?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingTop?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingRight?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingBottom?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingLeft?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingInline?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingInlineStart?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingInlineEnd?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  paddingBlock?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  margin?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  marginX?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  marginY?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  marginTop?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  marginRight?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  marginBottom?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  marginLeft?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  marginInlineStart?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  marginInlineEnd?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  top?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  right?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  bottom?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  left?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  gap?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  columnGap?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  rowGap?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number;
  background?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | tokens.ColorKey
    | ColorOpacityValue
    | "transparent"
    | "inherit"
    | "currentcolor";
  backgroundColor?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | tokens.ColorKey
    | ColorOpacityValue
    | "transparent"
    | "inherit"
    | "currentcolor";
  backgroundPosition?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue;
  backgroundSize?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | PxValue
    | AnyStringValue
    | "auto"
    | "cover"
    | "contain"
    | "inherit";
  color?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | tokens.ColorKey
    | ColorOpacityValue
    | "transparent"
    | "inherit"
    | "currentcolor";
  borderColor?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | tokens.ColorKey
    | ColorOpacityValue
    | "transparent"
    | "inherit"
    | "currentcolor";
  accentColor?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | tokens.ColorKey
    | ColorOpacityValue
    | "transparent"
    | "inherit"
    | "currentcolor";
  cornerShape?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "superellipse" | "inherit";
  borderRadius?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  borderRadiusStart?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  borderRadiusEnd?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  borderRadiusTop?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  borderRadiusBottom?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  borderRadiusRight?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  borderRadiusLeft?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  border?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  borderWidth?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderTopWidth?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderRightWidth?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderBottomWidth?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderLeftWidth?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderStyle?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "hidden"
    | "dotted"
    | "dashed"
    | "solid"
    | "double"
    | "groove"
    | "ridge"
    | "inset"
    | "outset"
    | "inherit";
  font?: tokens.FontFamilyKey | RawValue | CssVarStrValue | "inherit" | "initial" | "unset";
  fontFamily?: tokens.FontFamilyKey | RawValue | CssVarStrValue | CssVarValue | CssExprValue | "inherit" | "initial" | "unset";
  fontSize?: tokens.FontSizeKey | RawValue | CssVarStrValue | CssVarValue | CssExprValue | "inherit" | "initial" | "unset";
  fontWeight?:
    | tokens.FontWeightKey
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "inherit"
    | "initial"
    | "unset"
    | "bolder"
    | "lighter";
  fontStyle?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "normal" | "italic" | "oblique" | "inherit" | "initial" | "unset";
  lineHeight?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | "inherit"
    | "normal"
    | "none"
    | "shorter"
    | "short"
    | "tall"
    | "taller";
  textAlign?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "left" | "right" | "center" | "justify" | "inherit";
  outline?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "none" | "auto";
  cursor?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "not-allowed" | "pointer" | "default" | "inherit";
  width?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | PxValue
    | "full"
    | "auto"
    | "fit-content"
    | "full-dvh"
    | "full-dvw";
  height?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | PxValue
    | "full"
    | "auto"
    | "fit-content"
    | "full-dvh"
    | "full-dvw";
  minWidth?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | PxValue
    | "full"
    | "auto"
    | "fit-content"
    | "full-dvh"
    | "full-dvw";
  minHeight?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | PxValue
    | "full"
    | "auto"
    | "fit-content"
    | "full-dvh"
    | "full-dvw";
  maxWidth?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | PxValue
    | "full"
    | "auto"
    | "fit-content"
    | "full-dvh"
    | "full-dvw";
  maxHeight?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | PxValue
    | "full"
    | "auto"
    | "fit-content"
    | "full-dvh"
    | "full-dvw";
  display?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "block"
    | "flex"
    | "inline-flex"
    | "grid"
    | "none"
    | "listItem"
    | "inline"
    | "inlineBlock"
    | "inlineGrid";
  position?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "static" | "relative" | "absolute" | "fixed" | "sticky";
  inset?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  insetBlock?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  insetBlockStart?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  insetBlockEnd?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  insetInline?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  insetInlineStart?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  insetInlineEnd?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  pointerEvents?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "none" | "inherit";
  content?: AnyStringValue | CssVarStrValue | CssVarValue | CssExprValue | "empty";
  textDecoration?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "underline"
    | "overline"
    | "lineThrough"
    | "blink"
    | "inherit"
    | "underlineDotted"
    | "underlineDashed"
    | "underlineWavy";
  textTransform?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "none" | "capitalize" | "uppercase" | "lowercase" | "inherit";
  textOverflow?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "clip" | "ellipsis" | "inherit";
  overflow?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "hidden" | "scroll" | "visible" | "inherit";
  overflowX?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "hidden" | "scroll" | "visible" | "inherit";
  overflowY?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "hidden" | "scroll" | "visible" | "inherit";
  flexDirection?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "row" | "rowReverse" | "column" | "columnReverse" | "inherit";
  alignItems?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "start" | "end" | "center" | "baseline" | "stretch" | "inherit";
  alignContent?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "normal"
    | "start"
    | "end"
    | "center"
    | "space-between"
    | "space-around"
    | "space-evenly"
    | "stretch"
    | "inherit";
  alignSelf?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "auto"
    | "normal"
    | "start"
    | "end"
    | "center"
    | "baseline"
    | "stretch"
    | "inherit";
  justifyContent?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "inherit"
    | "flex-start"
    | "flex-end"
    | "safe flex-end"
    | "center"
    | "safe center"
    | "space-between"
    | "space-around"
    | "space-evenly"
    | "stretch"
    | "baseline"
    | "normal";
  justifyItems?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "normal" | "start" | "end" | "center" | "stretch" | "inherit";
  justifySelf?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "auto"
    | "normal"
    | "start"
    | "end"
    | "center"
    | "stretch"
    | "inherit";
  flexWrap?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "nowrap" | "wrap" | "wrapReverse" | "inherit";
  flex?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "inherit" | "initial" | "unset";
  flexGrow?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "auto" | "inherit";
  flexShrink?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "auto" | "inherit";
  flexBasis?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | number
    | PxValue
    | "full"
    | "auto"
    | "fit-content"
    | "full-dvh"
    | "full-dvw";
  order?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "initial" | "unset";
  placeItems?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "start"
    | "end"
    | "center"
    | "safe end"
    | "safe center"
    | "baseline"
    | "stretch"
    | "inherit";
  placeContent?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "normal"
    | "start"
    | "end"
    | "center"
    | "space-between"
    | "space-around"
    | "space-evenly"
    | "stretch"
    | "inherit";
  placeSelf?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "auto"
    | "normal"
    | "start"
    | "end"
    | "center"
    | "stretch"
    | "inherit";
  colorScheme?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "light" | "dark" | "inherit";
  appearance?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "none" | "auto" | "inherit" | "button";
  gridTemplateColumns?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | AnyStringValue | "none" | "auto";
  gridTemplateRows?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | AnyStringValue | "none" | "auto";
  gridTemplateAreas?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue;
  gridAutoColumns?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | AnyStringValue | "none" | "auto";
  gridAutoRows?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | AnyStringValue | "none" | "auto";
  gridAutoFlow?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "row"
    | "column"
    | "dense"
    | "row dense"
    | "column dense"
    | "inherit";
  gridColumn?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "auto";
  gridRow?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "auto";
  transition?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "inherit" | "initial" | "unset";
  opacity?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "initial" | "unset";
  visibility?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "visible" | "hidden" | "collapse" | "inherit";
  userSelect?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "text" | "none" | "all" | "contain" | "inherit";
  aspectRatio?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | AnyStringValue | "auto" | "inherit" | "initial" | "unset";
  objectFit?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "fill" | "contain" | "cover" | "none" | "scale-down" | "inherit";
  objectPosition?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "inherit";
  filter?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "none" | "inherit";
  backdropFilter?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "none" | "inherit";
  scrollbarWidth?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "none" | "thin" | "auto" | "inherit";
  scrollBehavior?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "smooth" | "inherit";
  overscrollBehavior?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "contain" | "none" | "inherit";
  overscrollBehaviorX?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "contain" | "none" | "inherit";
  overscrollBehaviorY?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "contain" | "none" | "inherit";
  scrollSnapType?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "x"
    | "y"
    | "both"
    | "block"
    | "inline"
    | "mandatory"
    | "proximity"
    | "inherit";
  scrollSnapAlign?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "none" | "start" | "end" | "center" | "inherit";
  scrollSnapStop?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "normal" | "always" | "inherit";
  resize?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "none" | "both" | "horizontal" | "vertical" | "inherit";
  caretColor?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | tokens.ColorKey
    | ColorOpacityValue
    | "transparent"
    | "inherit"
    | "currentcolor";
  verticalAlign?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "baseline" | "top" | "middle" | "bottom" | "inherit";
  zIndex?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "inherit" | "initial" | "unset";
  transform?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "inherit" | "initial" | "unset";
  translate?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "inherit" | "initial" | "unset";
  outlineWidth?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  outlineColor?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | tokens.ColorKey
    | ColorOpacityValue
    | "transparent"
    | "inherit"
    | "currentcolor";
  outlineStyle?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "hidden"
    | "dotted"
    | "dashed"
    | "solid"
    | "double"
    | "groove"
    | "ridge"
    | "inset"
    | "outset"
    | "inherit";
  outlineOffset?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  boxSizing?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "content-box" | "border-box" | "inherit";
  tabSize?: string | number;
  fontFeatureSettings?: string | number;
  fontVariationSettings?: string | number;
  textIndent?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  borderCollapse?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "collapse" | "separate" | "inherit";
  listStyle?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | AnyStringValue
    | "none"
    | "disc"
    | "circle"
    | "square"
    | "decimal"
    | "inherit";
  boxShadow?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | tokens.ShadowKey | "none" | "inherit";
  letterSpacing?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | number | "normal" | "inherit";
  clip?: CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue | "auto" | "inherit";
  whiteSpace?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "normal" | "nowrap" | "pre" | "preLine" | "preWrap" | "inherit";
  tableLayout?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "fixed" | "inherit";
  isolation?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "isolate" | "inherit";
  mixBlendMode?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "normal"
    | "multiply"
    | "screen"
    | "overlay"
    | "darken"
    | "lighten"
    | "color-dodge"
    | "color-burn"
    | "hardLight"
    | "softLight"
    | "difference"
    | "exclusion"
    | "hue"
    | "saturation"
    | "color"
    | "luminosity"
    | "inherit";
  willChange?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue;
  wordBreak?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "normal" | "break-all" | "keep-all" | "break-word" | "inherit";
  overflowWrap?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "normal" | "break-word" | "anywhere" | "inherit";
  positionArea?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "center"
    | "top"
    | "bottom"
    | "left"
    | "right"
    | "top left"
    | "top right"
    | "bottom left"
    | "bottom right"
    | "top span-all"
    | "bottom span-all"
    | "inherit"
    | "initial"
    | "unset";
  WebkitTextSizeAdjust?: string | number;
  WebkitTapHighlightColor?: string | number;
  WebkitOverflowScrolling?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "auto" | "touch" | "inherit";
  WebkitTextDecoration?:
    | RawValue
    | CssVarStrValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "underline"
    | "overline"
    | "lineThrough"
    | "blink"
    | "inherit"
    | "underlineDotted"
    | "underlineDashed"
    | "underlineWavy";
  WebkitAppearance?: RawValue | CssVarStrValue | CssVarValue | CssExprValue | "none" | "auto" | "inherit" | "button";
}

export type CssVarType = CssVarStrValue | CssVarValue | CssExprValue | AnyStringValue;
