// This file is auto-generated by scripts/cssProperties.ts. Do not edit manually.
import type { tokens } from "@dldc/hono-ui";
import type { AnyStringValue, ColorOpacityValue, CssExprValue, CssVarValue, PxValue, RawValue } from "./datatypes.ts";

export interface CssObjProperties {
  padding?: RawValue | CssVarValue | CssExprValue | number;
  paddingX?: RawValue | CssVarValue | CssExprValue | number;
  paddingY?: RawValue | CssVarValue | CssExprValue | number;
  paddingTop?: RawValue | CssVarValue | CssExprValue | number;
  paddingRight?: RawValue | CssVarValue | CssExprValue | number;
  paddingBottom?: RawValue | CssVarValue | CssExprValue | number;
  paddingLeft?: RawValue | CssVarValue | CssExprValue | number;
  paddingInline?: RawValue | CssVarValue | CssExprValue | number;
  paddingInlineStart?: RawValue | CssVarValue | CssExprValue | number;
  paddingInlineEnd?: RawValue | CssVarValue | CssExprValue | number;
  paddingBlock?: RawValue | CssVarValue | CssExprValue | number;
  margin?: RawValue | CssVarValue | CssExprValue | number;
  marginX?: RawValue | CssVarValue | CssExprValue | number;
  marginY?: RawValue | CssVarValue | CssExprValue | number;
  marginTop?: RawValue | CssVarValue | CssExprValue | number;
  marginRight?: RawValue | CssVarValue | CssExprValue | number;
  marginBottom?: RawValue | CssVarValue | CssExprValue | number;
  marginLeft?: RawValue | CssVarValue | CssExprValue | number;
  marginInlineStart?: RawValue | CssVarValue | CssExprValue | number;
  marginInlineEnd?: RawValue | CssVarValue | CssExprValue | number;
  top?: RawValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  right?: RawValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  bottom?: RawValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  left?: RawValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  gap?: RawValue | CssVarValue | CssExprValue | number;
  columnGap?: RawValue | CssVarValue | CssExprValue | number;
  rowGap?: RawValue | CssVarValue | CssExprValue | number;
  background?: RawValue | CssVarValue | CssExprValue | tokens.ColorKey | ColorOpacityValue | "transparent" | "inherit" | "currentcolor";
  backgroundColor?:
    | RawValue
    | CssVarValue
    | CssExprValue
    | tokens.ColorKey
    | ColorOpacityValue
    | "transparent"
    | "inherit"
    | "currentcolor";
  color?: RawValue | CssVarValue | CssExprValue | tokens.ColorKey | ColorOpacityValue | "transparent" | "inherit" | "currentcolor";
  borderColor?: RawValue | CssVarValue | CssExprValue | tokens.ColorKey | ColorOpacityValue | "transparent" | "inherit" | "currentcolor";
  cornerShape?: RawValue | CssVarValue | CssExprValue | "superellipse" | "inherit";
  rounded?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  roundedStart?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  roundedEnd?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  roundedTop?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  roundedBottom?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  roundedRight?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  roundedLeft?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  border?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "full" | "none";
  borderWidth?: RawValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderTopWidth?: RawValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderRightWidth?: RawValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderBottomWidth?: RawValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderLeftWidth?: RawValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  borderStyle?:
    | RawValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "hidden"
    | "dotted"
    | "dashed"
    | "solid"
    | "double"
    | "groove"
    | "ridge"
    | "inset"
    | "outset"
    | "inherit";
  font?: tokens.FontFamilyKey | RawValue | CssVarValue | "inherit" | "initial" | "unset";
  fontFamily?: tokens.FontFamilyKey | RawValue | CssVarValue | CssExprValue | "inherit" | "initial" | "unset";
  fontSize?: tokens.FontSizeKey | RawValue | CssVarValue | CssExprValue | "inherit" | "initial" | "unset";
  fontWeight?: tokens.FontWeightKey | RawValue | CssVarValue | CssExprValue | "inherit" | "initial" | "unset" | "bolder" | "lighter";
  lineHeight?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "normal" | "none" | "shorter" | "short" | "tall" | "taller";
  textAlign?: RawValue | CssVarValue | CssExprValue | "left" | "right" | "center" | "justify" | "inherit";
  outline?: RawValue | CssVarValue | CssExprValue | "none" | "auto";
  cursor?: RawValue | CssVarValue | CssExprValue | "not-allowed" | "pointer" | "default" | "inherit";
  width?: RawValue | CssVarValue | CssExprValue | number | PxValue | "full" | "auto" | "fit-content" | "full-dvh" | "full-dvw";
  height?: RawValue | CssVarValue | CssExprValue | number | PxValue | "full" | "auto" | "fit-content" | "full-dvh" | "full-dvw";
  minWidth?: RawValue | CssVarValue | CssExprValue | number | PxValue | "full" | "auto" | "fit-content" | "full-dvh" | "full-dvw";
  minHeight?: RawValue | CssVarValue | CssExprValue | number | PxValue | "full" | "auto" | "fit-content" | "full-dvh" | "full-dvw";
  maxWidth?: RawValue | CssVarValue | CssExprValue | number | PxValue | "full" | "auto" | "fit-content" | "full-dvh" | "full-dvw";
  maxHeight?: RawValue | CssVarValue | CssExprValue | number | PxValue | "full" | "auto" | "fit-content" | "full-dvh" | "full-dvw";
  display?:
    | RawValue
    | CssVarValue
    | CssExprValue
    | "block"
    | "flex"
    | "inline-flex"
    | "grid"
    | "none"
    | "listItem"
    | "inline"
    | "inlineBlock"
    | "inlineGrid";
  position?: RawValue | CssVarValue | CssExprValue | "static" | "relative" | "absolute" | "fixed" | "sticky";
  inset?: RawValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  pointerEvents?: RawValue | CssVarValue | CssExprValue | "auto" | "none" | "inherit";
  content?: AnyStringValue | CssVarValue | CssExprValue | "empty";
  textDecoration?:
    | RawValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "underline"
    | "overline"
    | "lineThrough"
    | "blink"
    | "inherit"
    | "underlineDotted"
    | "underlineDashed"
    | "underlineWavy";
  overflow?: RawValue | CssVarValue | CssExprValue | "auto" | "hidden" | "scroll" | "visible" | "inherit";
  overflowX?: RawValue | CssVarValue | CssExprValue | "auto" | "hidden" | "scroll" | "visible" | "inherit";
  overflowY?: RawValue | CssVarValue | CssExprValue | "auto" | "hidden" | "scroll" | "visible" | "inherit";
  flexDirection?: RawValue | CssVarValue | CssExprValue | "row" | "rowReverse" | "column" | "columnReverse" | "inherit";
  alignItems?: RawValue | CssVarValue | CssExprValue | "start" | "end" | "center" | "baseline" | "stretch" | "inherit";
  justifyContent?:
    | RawValue
    | CssVarValue
    | CssExprValue
    | "inherit"
    | "flex-start"
    | "flex-end"
    | "safe flex-end"
    | "center"
    | "safe center"
    | "space-between"
    | "space-around"
    | "space-evenly"
    | "stretch"
    | "baseline"
    | "normal";
  flexWrap?: RawValue | CssVarValue | CssExprValue | "nowrap" | "wrap" | "wrapReverse" | "inherit";
  flex?: RawValue | CssVarValue | CssExprValue | AnyStringValue | "inherit" | "initial" | "unset";
  flexGrow?: RawValue | CssVarValue | CssExprValue | number | "auto" | "inherit";
  flexShrink?: RawValue | CssVarValue | CssExprValue | number | "auto" | "inherit";
  colorScheme?: RawValue | CssVarValue | CssExprValue | "light" | "dark" | "inherit";
  appearance?: RawValue | CssVarValue | CssExprValue | "none" | "auto" | "inherit" | "button";
  gridTemplateColumns?: RawValue | CssVarValue | CssExprValue | number | AnyStringValue | "none" | "auto";
  gridTemplateRows?: RawValue | CssVarValue | CssExprValue | number | AnyStringValue | "none" | "auto";
  gridColumn?: RawValue | CssVarValue | CssExprValue | AnyStringValue | "auto";
  gridRow?: RawValue | CssVarValue | CssExprValue | AnyStringValue | "auto";
  transition?: RawValue | CssVarValue | CssExprValue | AnyStringValue | "inherit" | "initial" | "unset";
  opacity?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "initial" | "unset";
  scrollbarWidth?: RawValue | CssVarValue | CssExprValue | "none" | "thin" | "auto" | "inherit";
  resize?: RawValue | CssVarValue | CssExprValue | "none" | "both" | "horizontal" | "vertical" | "inherit";
  caretColor?: RawValue | CssVarValue | CssExprValue | tokens.ColorKey | ColorOpacityValue | "transparent" | "inherit" | "currentcolor";
  verticalAlign?: RawValue | CssVarValue | CssExprValue | "baseline" | "top" | "middle" | "bottom" | "inherit";
  zIndex?: RawValue | CssVarValue | CssExprValue | number | "inherit" | "initial" | "unset";
  transform?: RawValue | CssVarValue | CssExprValue | AnyStringValue | "inherit" | "initial" | "unset";
  translate?: RawValue | CssVarValue | CssExprValue | AnyStringValue | "inherit" | "initial" | "unset";
  outlineWidth?: RawValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  outlineColor?: RawValue | CssVarValue | CssExprValue | tokens.ColorKey | ColorOpacityValue | "transparent" | "inherit" | "currentcolor";
  outlineStyle?:
    | RawValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "hidden"
    | "dotted"
    | "dashed"
    | "solid"
    | "double"
    | "groove"
    | "ridge"
    | "inset"
    | "outset"
    | "inherit";
  outlineOffset?: RawValue | CssVarValue | CssExprValue | PxValue | "inherit" | "full" | "none";
  boxSizing?: RawValue | CssVarValue | CssExprValue | "content-box" | "border-box" | "inherit";
  tabSize?: string | number;
  fontFeatureSettings?: string | number;
  fontVariationSettings?: string | number;
  textIndent?: RawValue | CssVarValue | CssExprValue | number | PxValue | "auto";
  borderCollapse?: RawValue | CssVarValue | CssExprValue | AnyStringValue | "collapse" | "separate" | "inherit";
  listStyle?: RawValue | CssVarValue | CssExprValue | AnyStringValue | "none" | "disc" | "circle" | "square" | "decimal" | "inherit";
  boxShadow?: RawValue | CssVarValue | CssExprValue | tokens.ShadowKey | "none" | "inherit";
  letterSpacing?: RawValue | CssVarValue | CssExprValue | number | "normal" | "inherit";
  WebkitTextSizeAdjust?: string | number;
  WebkitTapHighlightColor?: string | number;
  WebkitOverflowScrolling?: RawValue | CssVarValue | CssExprValue | "auto" | "touch" | "inherit";
  WebkitTextDecoration?:
    | RawValue
    | CssVarValue
    | CssExprValue
    | "none"
    | "underline"
    | "overline"
    | "lineThrough"
    | "blink"
    | "inherit"
    | "underlineDotted"
    | "underlineDashed"
    | "underlineWavy";
  WebkitAppearance?: RawValue | CssVarValue | CssExprValue | "none" | "auto" | "inherit" | "button";
}

export type CssVar = CssVarValue | CssExprValue | AnyStringValue;
