import { resolve } from "@std/path";
import { PROPERTIES_CONFIG, VARIABLE_TYPE } from "../src/css/properties.ts";
import type { Datatype } from "../src/css/types.ts";

const outfile = resolve("src/css/types.gen.ts");

const imports = [
  `import type { tokens } from "@dldc/hono-ui";`,
  `import type { AnyStringValue, ColorOpacityValue, CssExprValue, CssVarStrValue, CssVarValue, PxValue, RawValue } from "./mappers.ts";`,
];

const content = [
  `// This file is auto-generated by scripts/cssProperties.ts. Do not edit manually.`,
  ...imports,
  ``,
  `export interface CssObjProperties {`,
  ...Object.entries(PROPERTIES_CONFIG).map(([property, config]) => {
    return `  ${toPropertyName(property)}?: ${datatypeTypes(config.datatype)};`;
  }),
  `}`,
  ``,
  `export type CssVarType = ${datatypeTypes(VARIABLE_TYPE)};`,
];

function datatypeTypes(datatype: Datatype | undefined): string {
  if (!datatype) {
    return "string | number";
  }
  const staticValues = Array.isArray(datatype.staticValues)
    ? Object.fromEntries(datatype.staticValues.map((v) => [v, v]))
    : datatype.staticValues ?? {};
  const staticTypes = Object.keys(staticValues).map((v) => `'${v}'`);
  const allTypes = [
    ...datatype.mappers.flatMap((mapper) => mapper.types),
    ...staticTypes,
  ];

  return allTypes.join(" | ");
}

function toPropertyName(val: string): string {
  if (/^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(val)) {
    return val;
  } else {
    return JSON.stringify(val);
  }
}

await Deno.writeTextFile(outfile, content.join("\n"));
await new Deno.Command("deno", { args: ["fmt", outfile] }).output();

console.log(`Generated CSS properties types at ${outfile}`);
